inherit_from: ../hitobito/.rubocop.yml

AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - db/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - spec/**/*
    - test/**/*

# we inherit mostly from CrudController et al, rendering this useless
Rails/LexicallyScopedActionFilter:
  Enabled: false
